CREATE TABLE CALENDAR(
	ID NUMBER PRIMARY KEY,
	GROUPID NUMBER,
	TITLE VARCHAR2(50) NOT NULL,
	WRITER VARCHAR2(50) NOT NULL,
	DESCRIPTION VARCHAR2(1000),
	"START" DATE NOT NULL,
	"END" DATE NOT NULL,
	DELFLAG CHAR(1) DEFAULT 'N'
);
CREATE SEQUENCE CAL_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO calendar values(cal_seq.nextval,'','할일title','김우연', '내용-content',to_date('2022/05/07','YYYY/MM/DD'), to_date('2022/05/08','YYYY/MM/DD'),'N');
INSERT INTO calendar values(cal_seq.nextval,'','[뚜잇뚜잇]캘린더 테스트입니다.','김우연', '프로젝트 화이팅',to_date('2022/05/07093000','YYYY/MM/DD HH24/MI/SS'), to_date('2022/05/07132500','YYYY/MM/DD HH24/MI/SS'),'N');

SELECT TO_DATE('202205070908','YYYY/MM/DD HH24:MI') FROM dual;

SELECT ID, GROUPID, TITLE, WRITER, DESCRIPTION, TO_CHAR("START", 'YYYY-MM-DD"T"HH24:MI:SS') AS "START",
 TO_CHAR("END", 'YYYY-MM-DD"T"HH24:MI:SS') AS "END"
 FROM CALENDAR
 WHERE DELFLAG = 'N'

SELECT 1 AS ENABLED FROM DUAL;

SELECT SEQ , ID, TITLE,  1 AS ENABLED
	FROM SPRINGBOARD s ;
	
SELECT CASE WHEN TO_CHAR(SYSDATE, 'DD') = '10' THEN 
	FROM DUAL;

CREATE SEQUENCE TEST_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 8;

SELECT  FROM DUAL;
	
SELECT DEPTNO, CASE DEPTNO WHEN 20 THEN '01'||TO_CHAR(SYSDATE, 'YYMMDD') END
	FROM EMP;

INSERT INTO GD.GDUSER(ID) VALUES((SELECT CASE DEPTNO WHEN 20 THEN '01'||TO_CHAR(SYSDATE, 'YYMMDD') END
	FROM EMP WHERE EMPNO='7369'));

SELECT DEPTNO, CASE DEPTNO WHEN 20 THEN TO_CHAR(SYSDATE, 'YYMMDD')||
			   CASE LENGTH(TEST_SEQ.NEXTVAL) WHEN 1 THEN '0'||TEST_SEQ.NEXTVAL ELSE TO_CHAR(TEST_SEQ.NEXTVAL) END 
			   END
	FROM EMP WHERE EMPNO='7369';





SELECT DEPTNO, CASE DEPTNO WHEN 20 THEN TO_CHAR(SYSDATE, 'YYMMDD')||(SELECT CASE LENGTH(TEST_SEQ.NEXTVAL) WHEN 1 THEN '0'||TO_CHAR(TEST_SEQ.NEXTVAL) END
	FROM DUAL) END
	FROM EMP WHERE EMPNO='7369';

INSERT INTO GD.GDUSER(ID) VALUES(TEST_SEQ.NEXTVAL);

SELECT CASE LENGTH(TEST_SEQ.NEXTVAL) WHEN 1 THEN '0'||TEST_SEQ.NEXTVAL ELSE TO_CHAR(TEST_SEQ.NEXTVAL) END
	FROM DUAL;


CREATE SEQUENCE TEST_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99 CYCLE CACHE 2;

SELECT TEST_SEQ.NEXTVAL FROM DUAL;
	
SELECT DEPTNO
	FROM EMP
	WHERE EMPNO='7369';

SELECT ID, GROUPID, TITLE, WRITER, DESCRIPTION, TO_CHAR("START", 'YYYY-MM-DD"T"HH24:MI:SS') AS "START",
 TO_CHAR("END", 'YYYY-MM-DD"T"HH24:MI:SS') AS "END"
 FROM CALENDAR ;
 
DELETE FROM CALENDAR c WHERE WRITER ='김우연';

UPDATE CALENDAR SET DELFLAG = 'Y' WHERE ID='48';

SELECT TO_DATE('202205120930','YYYY/MM/DD HH24:MI')
	FROM DUAL;
	
-- 드래그하여 날짜 업데이트
UPDATE CALENDAR SET "START" = TO_DATE('202205120930','YYYY/MM/DD HH24:MI'), "END" = TO_DATE('202205121530','YYYY/MM/DD HH24:MI')
	WHERE ID=30;

-- 내용, start, end 업데이트
UPDATE CALENDAR SET TITLE='안녕디지몬', "START" = TO_DATE('202205120930','YYYY/MM/DD HH24:MI'), "END" = TO_DATE('202205121530','YYYY/MM/DD HH24:MI')
	WHERE ID=30;
	
